### ISSUE TITLE
saliency&(224,224)

### ISSUE THREAD

**Issue by cherryolg** [bcmi/Image-Composition-Assessment-Dataset-CADB#6]
Hello, author. I don't quite understand a few questions. I would appreciate it if you could give me an answer.
(1) Why is the size of saliency map set to 8 times that of feature map?
(2) Why is the image size fixed at (224,224)? Can it be any input size?

**Comment by bo-zhang-cs** [comment]
Hi, cherryolg.
1) Setting the size of saliency map to 8 times that of feature map is to control the dimension of saliency feature in SAMP module, so that the dimensions of saliency vector is comparable to the dimension of partition feature.
2) As mentioned in our paper, we set the image size as 224×224 following previous works.  In theory our method is suitable for arbitrary input resolutions, but some parts of this code (_e.g._, SAMP module) may require minor modifications to keep the dimensions consistent and then the model should be retrained.
